#!/bin/sh

set -eu

cd "$(dirname "$0")"

careful_link () {
  local SRC=$1
  local DST=$2
  if [ -e "$DST" ] && [ ! -h "$DST" ]; then
    echo "${DST} exists and not a symlink, skipping..." >&2
  else
    ln -snf "$SRC" "$DST"
  fi
}

for filename in _*; do
  SRC="$(pwd)/${filename}"
  DST="${HOME}/.${filename#_}"
  echo "linking $SRC to $DST" >&2
  careful_link "$SRC" "$DST"
done
