##
## ZSH environment setup (.zshenv)
##
zdotdir=$HOME

umask u=rwx,g=rx,o=rx
setopt noglobalrcs

# Set path to contain only unique elements, and then set a sensible default.
typeset -U path
path=( ~/.nodenv/bin(N)
       ~/local/{,s}bin(N)
       /usr/texbin
       /usr/local/{,s}bin(N)
       /usr/{,s}bin(N)
       /{,s}bin(N)
     )

export EMAIL="Nick Stenning <nick@whiteink.com>"
export MAILDIR="${HOME}/.mail"
export NOTESDIR="${HOME}/Dropbox/data/notes"
export VAULTSDIR="${HOME}/Dropbox/data/vaults"

# Keychain
export KEYCHAIN_DEFAULT_KEYS="D1BEB004 $(hostname -s) gds id_rsa id_dsa"

# Editor
export EDITOR="vim"
export VISUAL="vim"
export TEXEDIT="${EDITOR} +%d %s"
export LESSEDIT="${EDITOR} ?lm+%lm. %f"
export PAGER="less"
export LESS="-R --ignore-case --long-prompt"

# Set UTF8 for terminals
unset LC_ALL
export LANG="en_GB.UTF-8"
export LC_COLLATE="C"

# Even if you're on BSD, you'll want to leave the Linux version here for zsh
# colour completion.
export LS_COLORS="no=00:fi=00:di=33:ln=36:ex=00;31:pi=35;40:so=35;40:bd=35;40:cd=35;40"
export LSCOLORS="dxgxfafabxfafaxbxbadad"

# Gnuplot
export GNUPLOT_LIB="${HOME}/.gnuplot.d:${GNUPLOT_LIB}"

# Virtualenv
export VIRTUALENV_USE_DISTRIBUTE="yes"

# Go
export GOPATH="${HOME}/code/go:${GOPATH}"
path=( ~/code/go/bin(N) $path )

# Git
export GIT_DISCOVERY_ACROSS_FILESYSTEM=1

# Vagrant
export VAGRANT_DEFAULT_PROVIDER="vmware_fusion"

dot () {
  [ -f "$1" ] && . "$1"
}

# boxen

dot /opt/boxen/env.sh

if which brew >/dev/null; then
  BREW_PREFIX=$(brew --prefix)

  path=(
    $path
  )
  fpath=($BREW_PREFIX/share/zsh-completions $fpath)

  # autoenv
  dot "$BREW_PREFIX/opt/autoenv/activate.sh"
  # virtualenv
  dot "$BREW_PREFIX/bin/virtualenvwrapper_lazy.sh"

  # pkg-config
  typeset -T PKG_CONFIG_PATH pkg_config_path
  typeset -U pkg_config_path
  pkg_config_path=( $BREW_PREFIX/{lib,share}/pkgconfig(/N) $pkg_config_path )
  export PKG_CONFIG_PATH
fi

if which nodenv >/dev/null; then
  eval "$(nodenv init -)"
fi

if which rbenv >/dev/null; then
  eval "$(rbenv init -)"
fi
