[ -z "$PS1" ] && return

ZSH=$HOME/src/dotfiles/zsh

# Report timing statistics for long-running processes
REPORTTIME=5
TIMEFMT="%J  %U user %S system %P cpu %MM memory %*E total"

# Load and run compinit
autoload -U compinit
compinit -i

# allow adding hooks in main files
autoload -U add-zsh-hook

# load main files
for file ($ZSH/lib/*.zsh(.xN)) source $file

# load keychain
if which keychain >/dev/null; then
  eval $(keychain -Q -q --eval --agents ssh --ignore-missing --timeout 43200 $(hostname -s) id_rsa)
fi

# z
dot "$BREW_PREFIX/etc/profile.d/z.sh"
