[ -z "$PS1" ] && return

ZSH=$HOME/src/dotfiles/zsh

# Report timing statistics for long-running processes
REPORTTIME=5
TIMEFMT="%J  %U user %S system %P cpu %MM memory %*E total"

# Load and run compinit
autoload -U compinit
compinit -i

# allow adding hooks in main files
autoload -U add-zsh-hook

# load main files
for file ($ZSH/lib/*.zsh(.xN)) source $file

# write path to mac environment file
if which defaults >/dev/null; then
  defaults write ~/.MacOSX/environment PATH "$PATH"
fi

# load keychain
if which keychain >/dev/null; then
  eval $(keychain -q --eval --noask --inherit any-once --ignore-missing --timeout 1440 ${=KEYCHAIN_DEFAULT_KEYS})
fi

# z
dot "$BREW_PREFIX/etc/profile.d/z.sh"
